export const ProductData = [
  {
    id: 1,
    sku: 23456789,
    title: "spyix T-shirt Dragon",
    quantity: 1,
    description: "spycho tie green",
    AvalibaleSizes: ["M", "XL", "XXL"],
    price: 10,
    isFreeShiping: true,
  },
  {
    id: 2,
    sku:211113423456789,
    title: "FullSend T-shirt Dragon",
    quantity: 1,
    description: "spycho tie green",
    AvalibaleSizes: ["S", "L", "XL"],
    price: 44,
    isFreeShiping: true,
  },
  {
    id: 3,
    sku: 12345556789,
    title: "Snake T-shirt Dragon",
    quantity: 1,
    description: "spycho tie green",
    AvalibaleSizes: ["M", "L", "XL"],
    price: 20,
    isFreeShiping: true,
  },
  {
    id: 4,
    sku: 234456756789,
    title: "Phonix T-shirt Dragon",
    quantity: 1,
    description: "spycho tie green",
    AvalibaleSizes: ["S", "L", "XXL"],
    price: 123,
    isFreeShiping: true,
  },
  {
    id: 5,
    sku: 234456756789,
    title: "Phonix T-shirt Dragon",
    quantity: 1,
    description: "spycho tie green",
    AvalibaleSizes: ["S", "L", "XL" , 'XXL'],
    price: 39,
    isFreeShiping: true,
  },
  {
    id: 6,
    sku: 234456756789,
    title: "Phonix T-shirt Dragon",
    quantity: 1,
    description: "spycho tie green",
    AvalibaleSizes: ["XS", "M", "XXL"],
    price: 49,
    isFreeShiping: true,
  },
];
